export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json }
  | Json[];

export interface Database {
  public: {
    Tables: {
      Courses: {
        Row: {
          all_course_codes: Json | null;
          areas: Json | null;
          average_gut_rating: number | null;
          average_professor: number | null;
          average_rating: number | null;
          average_rating_same_professors: number | null;
          average_workload: number | null;
          average_workload_same_professors: number | null;
          classnotes: string | null;
          course_code: string | null;
          course_id: number;
          credits: number | null;
          crn: number | null;
          description: string | null;
          enrolled: number | null;
          extra_info: string | null;
          final_exam: string | null;
          flag_info: Json | null;
          fysem: boolean | null;
          last_enrollment: number | null;
          last_enrollment_same_professors: boolean | null;
          last_offered_course_id: number | null;
          listing_id: number | null;
          locations_summary: string | null;
          number: string | null;
          professor_ids: Json | null;
          professor_names: Json | null;
          regnotes: string | null;
          requirements: string | null;
          rp_attr: string | null;
          same_course_and_profs_id: number | null;
          same_course_id: number | null;
          school: string | null;
          season_code: string | null;
          section: string | null;
          skills: Json | null;
          subject: string | null;
          syllabus_url: string | null;
          times_by_day: Json | null;
          times_summary: string | null;
          title: string | null;
        };
        Insert: {
          all_course_codes?: Json | null;
          areas?: Json | null;
          average_gut_rating?: number | null;
          average_professor?: number | null;
          average_rating?: number | null;
          average_rating_same_professors?: number | null;
          average_workload?: number | null;
          average_workload_same_professors?: number | null;
          classnotes?: string | null;
          course_code?: string | null;
          course_id: number;
          credits?: number | null;
          crn?: number | null;
          description?: string | null;
          enrolled?: number | null;
          extra_info?: string | null;
          final_exam?: string | null;
          flag_info?: Json | null;
          fysem?: boolean | null;
          last_enrollment?: number | null;
          last_enrollment_same_professors?: boolean | null;
          last_offered_course_id?: number | null;
          listing_id?: number | null;
          locations_summary?: string | null;
          number?: string | null;
          professor_ids?: Json | null;
          professor_names?: Json | null;
          regnotes?: string | null;
          requirements?: string | null;
          rp_attr?: string | null;
          same_course_and_profs_id?: number | null;
          same_course_id?: number | null;
          school?: string | null;
          season_code?: string | null;
          section?: string | null;
          skills?: Json | null;
          subject?: string | null;
          syllabus_url?: string | null;
          times_by_day?: Json | null;
          times_summary?: string | null;
          title?: string | null;
        };
        Update: {
          all_course_codes?: Json | null;
          areas?: Json | null;
          average_gut_rating?: number | null;
          average_professor?: number | null;
          average_rating?: number | null;
          average_rating_same_professors?: number | null;
          average_workload?: number | null;
          average_workload_same_professors?: number | null;
          classnotes?: string | null;
          course_code?: string | null;
          course_id?: number;
          credits?: number | null;
          crn?: number | null;
          description?: string | null;
          enrolled?: number | null;
          extra_info?: string | null;
          final_exam?: string | null;
          flag_info?: Json | null;
          fysem?: boolean | null;
          last_enrollment?: number | null;
          last_enrollment_same_professors?: boolean | null;
          last_offered_course_id?: number | null;
          listing_id?: number | null;
          locations_summary?: string | null;
          number?: string | null;
          professor_ids?: Json | null;
          professor_names?: Json | null;
          regnotes?: string | null;
          requirements?: string | null;
          rp_attr?: string | null;
          same_course_and_profs_id?: number | null;
          same_course_id?: number | null;
          school?: string | null;
          season_code?: string | null;
          section?: string | null;
          skills?: Json | null;
          subject?: string | null;
          syllabus_url?: string | null;
          times_by_day?: Json | null;
          times_summary?: string | null;
          title?: string | null;
        };
      };
      EvaluationNarratives: {
        Row: {
          comment: string;
          comment_compound: number;
          course_id: number;
          id: number;
        };
        Insert: {
          comment: string;
          comment_compound: number;
          course_id: number;
          id: number;
        };
        Update: {
          comment?: string;
          comment_compound?: number;
          course_id?: number;
          id?: number;
        };
      };
      UserCourse: {
        Row: {
          courseId: number;
          id: number;
          userEmail: string;
        };
        Insert: {
          courseId: number;
          id?: number;
          userEmail: string;
        };
        Update: {
          courseId?: number;
          id?: number;
          userEmail?: string;
        };
      };
    };
    Views: {
      Courses_3_Decimals: {
        Row: {
          all_course_codes: Json | null;
          areas: Json | null;
          average_gut_rating: number | null;
          average_professor: number | null;
          average_rating: number | null;
          average_rating_same_professors: number | null;
          average_workload: number | null;
          average_workload_same_professors: number | null;
          classnotes: string | null;
          course_code: string | null;
          course_id: number | null;
          credits: number | null;
          crn: number | null;
          description: string | null;
          enrolled: number | null;
          extra_info: string | null;
          final_exam: string | null;
          flag_info: Json | null;
          fysem: boolean | null;
          last_enrollment: number | null;
          last_enrollment_same_professors: boolean | null;
          last_offered_course_id: number | null;
          listing_id: number | null;
          locations_summary: string | null;
          number: string | null;
          professor_ids: Json | null;
          professor_names: Json | null;
          regnotes: string | null;
          requirements: string | null;
          rp_attr: string | null;
          same_course_and_profs_id: number | null;
          same_course_id: number | null;
          school: string | null;
          season_code: string | null;
          section: string | null;
          skills: Json | null;
          subject: string | null;
          syllabus_url: string | null;
          times_by_day: Json | null;
          times_summary: string | null;
          title: string | null;
        };
        Insert: {
          all_course_codes?: Json | null;
          areas?: Json | null;
          average_gut_rating?: never;
          average_professor?: never;
          average_rating?: never;
          average_rating_same_professors?: never;
          average_workload?: never;
          average_workload_same_professors?: never;
          classnotes?: string | null;
          course_code?: string | null;
          course_id?: number | null;
          credits?: never;
          crn?: number | null;
          description?: string | null;
          enrolled?: number | null;
          extra_info?: string | null;
          final_exam?: string | null;
          flag_info?: Json | null;
          fysem?: boolean | null;
          last_enrollment?: number | null;
          last_enrollment_same_professors?: boolean | null;
          last_offered_course_id?: number | null;
          listing_id?: number | null;
          locations_summary?: string | null;
          number?: string | null;
          professor_ids?: Json | null;
          professor_names?: Json | null;
          regnotes?: string | null;
          requirements?: string | null;
          rp_attr?: string | null;
          same_course_and_profs_id?: number | null;
          same_course_id?: number | null;
          school?: string | null;
          season_code?: string | null;
          section?: string | null;
          skills?: Json | null;
          subject?: string | null;
          syllabus_url?: string | null;
          times_by_day?: Json | null;
          times_summary?: string | null;
          title?: string | null;
        };
        Update: {
          all_course_codes?: Json | null;
          areas?: Json | null;
          average_gut_rating?: never;
          average_professor?: never;
          average_rating?: never;
          average_rating_same_professors?: never;
          average_workload?: never;
          average_workload_same_professors?: never;
          classnotes?: string | null;
          course_code?: string | null;
          course_id?: number | null;
          credits?: never;
          crn?: number | null;
          description?: string | null;
          enrolled?: number | null;
          extra_info?: string | null;
          final_exam?: string | null;
          flag_info?: Json | null;
          fysem?: boolean | null;
          last_enrollment?: number | null;
          last_enrollment_same_professors?: boolean | null;
          last_offered_course_id?: number | null;
          listing_id?: number | null;
          locations_summary?: string | null;
          number?: string | null;
          professor_ids?: Json | null;
          professor_names?: Json | null;
          regnotes?: string | null;
          requirements?: string | null;
          rp_attr?: string | null;
          same_course_and_profs_id?: number | null;
          same_course_id?: number | null;
          school?: string | null;
          season_code?: string | null;
          section?: string | null;
          skills?: Json | null;
          subject?: string | null;
          syllabus_url?: string | null;
          times_by_day?: Json | null;
          times_summary?: string | null;
          title?: string | null;
        };
      };
      EvaluationNarrativesToCourses: {
        Row: {
          all_course_codes: Json | null;
          areas: Json | null;
          average_gut_rating: number | null;
          average_professor: number | null;
          average_rating: number | null;
          average_rating_same_professors: number | null;
          average_workload: number | null;
          average_workload_same_professors: number | null;
          classnotes: string | null;
          comment: string | null;
          comment_compound: number | null;
          course_code: string | null;
          credits: number | null;
          crn: number | null;
          description: string | null;
          enrolled: number | null;
          extra_info: string | null;
          final_exam: string | null;
          flag_info: Json | null;
          fysem: boolean | null;
          id: number | null;
          last_enrollment: number | null;
          last_enrollment_same_professors: boolean | null;
          last_offered_course_id: number | null;
          listing_id: number | null;
          locations_summary: string | null;
          number: string | null;
          professor_ids: Json | null;
          professor_names: Json | null;
          regnotes: string | null;
          requirements: string | null;
          rp_attr: string | null;
          same_course_and_profs_id: number | null;
          same_course_id: number | null;
          school: string | null;
          season_code: string | null;
          section: string | null;
          skills: Json | null;
          subject: string | null;
          syllabus_url: string | null;
          times_by_day: Json | null;
          times_summary: string | null;
          title: string | null;
        };
      };
      EvaluationNarrativesToCourses202303: {
        Row: {
          all_course_codes: Json | null;
          areas: Json | null;
          comment: string | null;
          comment_compound: number | null;
          skills: Json | null;
          title: string | null;
        };
      };
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      [_ in never]: never;
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
}
