import { Course } from './course';

export type Catalog = Course[];
type CatalogKeys = keyof Course;
export const catalogKeys: CatalogKeys[] = [
  'course_code',
  'title',
  'all_course_codes',
  'areas',
  'average_rating',
  'average_rating_same_professors',
  'average_workload',
  'average_workload_same_professors',
  'average_gut_rating',
  'average_professor',
  // 'classnotes',
  // 'credits',
  // 'crn',
  // 'description',
  // 'enrolled',
  // 'extra_info',
  // 'final_exam',
  // 'flag_info',
  // 'fysem',
  // 'last_enrollment',
  // 'last_enrollment_same_professors',
  'listing_id',
  // 'locations_summary',
  // 'number',
  // 'professor_ids',
  // 'professor_names',
  // 'regnotes',
  // 'requirements',
  // 'rp_attr',
  // 'same_course_id',
  // 'same_course_and_profs_id',
  // 'last_offered_course_id',
  // 'school',
  // 'season_code',
  // 'section',
  // 'skills',
  // 'subject',
  // 'syllabus_url',
  // 'times_by_day',
  // 'times_summary',
];
